/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.server;

import java.util.concurrent.TimeUnit;

public class App {
    public static void main(String[] args) throws InterruptedException {
        Client c1 = new Client("c");
        //Client c2 = new Client("b");
        //Client c3 = new Client("a");
        c1.start();
        //TimeUnit.SECONDS.sleep(1);
        //c2.start();
        //TimeUnit.SECONDS.sleep(1);
        //c3.start();
    }

}
