/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.server;

public class App {

    public static void main(String[] args) {
        Server server = new Server();
        server.run();
    }
}
